services:
  todoendpoint:
    build:
      context: ../../TodoEndpoint
    image: todoendpoint
    container_name: todoendpoint
    ports:
      - "5000:80"
    depends_on:
      - todoui

  todoui:
    build:
      context: ../../TodoUI
    image: todoui
    container_name: todoui
    #ports: # For Debug
    #  - "5001:5000"
    environment:
      - urls=http://*:5000
      - todoapi=http://todoapi:5000/api/todoitems
    depends_on:
      - todoapi

  todoapi:
    build:
      context: ../../TodoApi
    image: todoapi
    container_name: todoapi
    #ports:# For Debug
    #  - "5002:5000"
    environment:
      - urls=http://*:5000
      - ConnectionStrings__MySQL=Server=tododb;Database=todoapi;User=todoapi;Password=todoapi;
    depends_on:
      - tododb

  tododb:
    image: mariadb
    container_name: tododb
    volumes:
      - type: volume
        source: tododb-data
        target: /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=todoapi
      - MYSQL_DATABASE=todoapi
      - MYSQL_USER=todoapi
      - MYSQL_PASSWORD=todoapi

  tododb-console:
    image: adminer
    container_name: tododb-console
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=tododb
    depends_on:
      - tododb


volumes:
  tododb-data:
    name: tododb-data
